-- Run this if you only created `snapshots` so far.
-- Safe to re-run: uses IF NOT EXISTS throughout.

CREATE TABLE IF NOT EXISTS snapshot_holders (
  snapshot_id BIGINT NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
  owner TEXT NOT NULL,
  token_account TEXT NOT NULL,
  raw_amount TEXT NOT NULL,
  ui_amount DOUBLE PRECISION NOT NULL,
  rank INTEGER NOT NULL,
  pct_supply DOUBLE PRECISION NOT NULL,
  historical_holding_since_at TIMESTAMPTZ,
  historical_holding_source TEXT,
  PRIMARY KEY (snapshot_id, owner)
);

CREATE INDEX IF NOT EXISTS idx_snapshot_holders_rank
  ON snapshot_holders(snapshot_id, rank);

CREATE TABLE IF NOT EXISTS wallet_holder_state (
  owner TEXT PRIMARY KEY,
  first_seen_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  current_streak_started_at TIMESTAMPTZ NOT NULL,
  last_snapshot_id BIGINT NOT NULL REFERENCES snapshots(id),
  is_current_holder BOOLEAN NOT NULL,
  peak_balance TEXT NOT NULL,
  latest_balance TEXT NOT NULL,
  historical_holding_since_at TIMESTAMPTZ,
  historical_holding_source TEXT,
  last_rank INTEGER
);

CREATE INDEX IF NOT EXISTS idx_wallet_holder_state_current
  ON wallet_holder_state(is_current_holder);

CREATE TABLE IF NOT EXISTS wallet_labels (
  owner TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  source TEXT NOT NULL,
  notes TEXT,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS snapshot_metrics (
  snapshot_id BIGINT PRIMARY KEY REFERENCES snapshots(id) ON DELETE CASCADE,
  metrics JSONB NOT NULL,
  distribution JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wallet_classifications (
  owner TEXT PRIMARY KEY,
  wallet_type TEXT NOT NULL CHECK (
    wallet_type IN ('wallet', 'liquidity_pool', 'program', 'unknown')
  ),
  classification_source TEXT NOT NULL,
  classification_confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
  exclude_from_holder_stats BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wallet_classifications_excluded
  ON wallet_classifications(exclude_from_holder_stats);

CREATE TABLE IF NOT EXISTS holder_count_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mint TEXT NOT NULL,
  holder_count INTEGER NOT NULL CHECK (holder_count >= 0),
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_holder_count_history_mint_scanned_at
  ON holder_count_history(mint, scanned_at DESC);

CREATE TABLE IF NOT EXISTS wallet_portfolio_cache (
  owner TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wallet_portfolio_cache_fetched_at
  ON wallet_portfolio_cache(fetched_at DESC);

-- Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';
