CREATE TABLE IF NOT EXISTS snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mint TEXT NOT NULL,
  slot BIGINT,
  status TEXT NOT NULL CHECK (status IN ('complete', 'partial', 'failed')),
  holder_count INTEGER NOT NULL,
  new_holder_count INTEGER NOT NULL DEFAULT 0,
  dropped_holder_count INTEGER NOT NULL DEFAULT 0,
  total_supply TEXT NOT NULL,
  decimals INTEGER NOT NULL,
  scanned_at TIMESTAMPTZ NOT NULL,
  source TEXT NOT NULL,
  error TEXT
);

CREATE INDEX IF NOT EXISTS idx_snapshots_scanned_at
  ON snapshots(scanned_at DESC);

CREATE TABLE IF NOT EXISTS snapshot_holders (
  snapshot_id BIGINT NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
  owner TEXT NOT NULL,
  token_account TEXT NOT NULL,
  raw_amount TEXT NOT NULL,
  ui_amount DOUBLE PRECISION NOT NULL,
  rank INTEGER NOT NULL,
  pct_supply DOUBLE PRECISION NOT NULL,
  historical_holding_since_at TIMESTAMPTZ,
  historical_holding_source TEXT,
  PRIMARY KEY (snapshot_id, owner)
);

CREATE INDEX IF NOT EXISTS idx_snapshot_holders_rank
  ON snapshot_holders(snapshot_id, rank);

CREATE TABLE IF NOT EXISTS wallet_holder_state (
  owner TEXT PRIMARY KEY,
  first_seen_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  current_streak_started_at TIMESTAMPTZ NOT NULL,
  last_snapshot_id BIGINT NOT NULL REFERENCES snapshots(id),
  is_current_holder BOOLEAN NOT NULL,
  peak_balance TEXT NOT NULL,
  latest_balance TEXT NOT NULL,
  historical_holding_since_at TIMESTAMPTZ,
  historical_holding_source TEXT
);

CREATE INDEX IF NOT EXISTS idx_wallet_holder_state_current
  ON wallet_holder_state(is_current_holder);

CREATE TABLE IF NOT EXISTS wallet_labels (
  owner TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  source TEXT NOT NULL,
  notes TEXT,
  updated_at TIMESTAMPTZ NOT NULL
);
