CREATE TABLE IF NOT EXISTS holder_count_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mint TEXT NOT NULL,
  holder_count INTEGER NOT NULL CHECK (holder_count >= 0),
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_holder_count_history_mint_scanned_at
  ON holder_count_history(mint, scanned_at DESC);
